# Generated by Django 5.0.3 on 2024-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_pong_players_pong_player1_pong_player2'),
        ('tournament', '0003_alter_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(related_name='games', to='pong.pong'),
        ),
    ]
