# Generated by Django 5.0.3 on 2024-03-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
