# Generated by Django 5.0.3 on 2024-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.BinaryField(blank=True, editable=True, max_length=20971520, null=True),
        ),
    ]
